---
version: 2.1

orbs:
  do: twdps/vault@dev:<<pipeline.git.revision>>
  op: twdps/onepassword@3.0.0

globals:
  - &context platform

commands:

  echo-message:
    parameters:
      msg:
        type: string
    steps:
      - run:
          name: echo msg
          command: echo "<< parameters.msg >>"

jobs:

  test versioned package install: 
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - do/install:
          vault-version: 1.19.3
          teller-version: 1.5.6
      - run:
          name: test version install
          command: |
            set -exo pipefail
            vault version | grep "1.19.3"
            teller version | grep "1.5.6"

  test commands:
    docker:
      - image: twdps/circleci-base-image:alpine-stable
    environment:
      HELLO_TEST: Hello
      WORLD_TEST: World
    steps:
      - checkout
      - do/tpl:
          tpl-path: test
          tpl-file: test-template.txt
          before-tpl:
            - echo-message:
                msg: "before tpl"
          after-tpl:
            - echo-message:
                msg: "before tpl"
      - run:
          name: check tpl results
          command: |
            cat test-template.txt | grep "Hello World!"

workflows:

  integration tests:
    jobs:
      - test versioned package install

      - test commands:
          context: *context

      # - do/slack:
      #     name: test slack bot job
      #     context: *context
      #     channel: lab-events
      #     message: orb-pipeline-events dev build test of slack message job with button
      #     include-link: true
      #     before-message:
      #       - op/env
      #       - echo-message:
      #           msg: "before slack message"
      #     after-message:
      #       - echo-message:
      #           msg: "after slack message"
